apiVersion: v1
kind: Pod
metadata:
  name: zabbix-proxy-pod
spec:
  containers:
  - name: zabbix-proxy-sqlite3 
    image: zabbix/zabbix-proxy-sqlite3:alpine-5.4.4

    ports:
    - protocol: TCP
      port: 10051
    
#      env: # defaults according to https://hub.docker.com/r/zabbix/zabbix-proxy-sqlite3
#      - name: ZBX_PROXYMODE
#        value: 0
#      - name: ZBX_HOSTNAME
#        value: "zabbix-proxy-sqlite3"
#      - name: ZBX_SERVER_HOST
#        value: "zabbix-server"
#      - name: ZBX_SERVER_PORT
#        value: 10051
#      - name: ZBX_LOADMODULE
#        value: ""
#      - name: ZBX_DEBUGLEVEL
#        value: 3
#      - name: ZBX_TIMEOUT
#        value: 4
#      - name: ZBX_JAVAGATEWAY_ENABLE
#        value: false
#      - name: ZBX_VAULTDBPATH
#        value: ""
#      - name: ZBX_VAULTURL
#        value: "https://127.0.0.1:8200"
#      - name: ZBX_ENABLEREMOTECOMMANDS
#        value: 0
#      - name: VAULT_TOKEN
#        value: ""
#      - name: ZBX_SOURCEIP
#        value: ""
#      - name: ZBX_HOSTNAMEITEM
#        value: "system.hostname"


#    resources:
#      request:
#        cpu: ???
#        memory: ???
#      limit:
#        cpu: ???
#        memory: ???

#    readinessProbe:
#      tcpSocket:
#        port: ???

#    livenessProbe:
#      tcpSocket:
#        port: ???   

    volumeMounts:
    - name: data
      mountPath: /data

  - name: zabbix-agent2
    image: zabbix/zabbix-agent2:alpine-5.4.4

  volumes:
  - name: data
    emptyDir: {} 


