apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-proxy-pod-pv
spec:
  storageClassName: 
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

